#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allclean
cp -r 0.org 0
# Set application name
application=$(getApplication)

runApplication chemkinToFoam \
               chemkin/chem.inp chemkin/therm.dat chemkin/transportProperties \
               constant/reactions constant/speciesThermo

blockMesh
setFields
decomposePar -force
runParallel $application

#------------------------------------------------------------------------------
